### ISSUE TITLE
Ubuntu dependencies

### ISSUE THREAD

**Issue by colindaven** [imgag/megSAP#1]
Hi, 

this is not an exhaustive list but might help others get up and running.

Required Ubuntu 16.04 packages.

sudo apt-get install git cmake build-essential qt5-qmake qt5-default qtbase5-dev libqt5xmlpatterns5 libqt5xmlpatterns5-dev lib64ncurses5-dev php7.0 php7.0-dev

Best wishes,
Colin

**Comment by imgag** [comment]
Thanks Colin!

I updated the main readme.md file accordingly:

Best,
  Marc
