### ISSUE TITLE
Chromosome blocks not continous

### ISSUE THREAD

**Issue by apeltzer** [imgag/megSAP#10]
Hi! 

we were able to run the most current version of the pipeline successfully in a Singularity container on an example dataset. This runs through QC, mapping and variant calling but fails in the very last (`tabix` step). The container has Ubuntu latest, with all dependencies installed properly and BAM files, VCF files look fine to me. Any guess whats happening here?

    PHP Notice:  Undefined index: target_file in /megSAP/src/Pipelines/analyze.php on line 111
    [E::hts_idx_push] chromosome blocks not continuous
    tbx_index_build failed: 
    Sample_Project04172015_20150062801/CMT_Project04172015_20150062801_var.vcf.gz
    ERROR: 'Call of external tool 'tabix' returned error code '1'.' in 
    /megSAP/src/Common/ToolBase.php:725.

**Comment by apeltzer** [comment]
I checked manually with Tabix v1.6 and it seems to produce the same error on the VCF.gz file

**Comment by imgag** [comment]
Hi Alexander,

I guess the VCF is not sorted for some reason.
Can you send me the file and the system INI file as well?

Best,
  Marc

**Comment by apeltzer** [comment]
Hi Marc,
you should just have received an e-mail with a TGZ file (containing INI and VCF.gz file)

**Comment by imgag** [comment]
Hi Alexander,

there was a bug in the special handling for chrM variant calling when no target region was given.
chrMT variants were twice in the variant list.

It should be fixed with the last commit.
Can you verify that? You need to run the "vc" step only.

Best,
  Marc

**Comment by apeltzer** [comment]
Hi Marc!
I'll test over night and will let you know tomorrow morning if things work now.

**Comment by apeltzer** [comment]
Hi Marc,

it works now and the VCF is sorted accordingly. 
Thanks!
Alex
