### ISSUE TITLE
Improve mosaik detection in somatic germline samples

### ISSUE THREAD

**Issue by axelgschwind** [imgag/megSAP#106]
Use freebayes with changed parameters or any other variant caller to detect variants with low B-allele frequencies.

Parameters:
- AF > 1-5%

Possible tools:
- freebayes (pooled continous, AO>=3)
- varscan 2
- GATK?

Controls:
were called in gsvar file:
sample | position - hg38 | position - hg19
---|---|----
DX192182 | chr17:7675148 G >T               | chr17:7578466 G > T
DX195628/DX195106 | chr3:179234297 A>G    | chr3:178952085 A>G
DX202629_01 | chr2:25240315 G>T             | chr2:25463184 G>T
DX207760_01 | chr17:7674220 C>T | 
DX208156_01 | chr11:108284303 ->T           | chr11:108155030 ->T
DX208986_01 | chr17:7674262  T>C             | chr17:7577580 T>C
DX2103796_01 | chr17:7675095 C>T            | chr17:7578413 C>T
DX2106763 | chr19:1226580 A>G             | chr19:1226579 A>G
DX171568/DX2108845/DX2108847 |  chr10:86192503 G>A | 
DX2108705_02 | chr7:152852240 G>A |

were not called in gsvar file:
sample | position - hg38 
---|----
DX2108704_02(11%) | chr7:152852240 G>A 
DX171568_02 (1%)  | chr10:87952260 G>A 
DX173692_01 (7%)  | chr10:87952260 G>A 
DX2107524_01 (2%) | chr3:179234297 A > G
DX2202122_01 (2.4%) | chr12:25245328 C>G

Additional test data:
- Monzygotic Twins in projects "I19D021_Olaf-Zwillinge"

**Comment by Ott-Alexander** [comment]
Controls:
were called in gsvar file:
lifted positions - hg38 | old position - hg19
---|----
DX192182 chr17:7675148 G >T               | chr17:7578466 G > T
DX195628/DX195106 chr3:179234297 A > G    | chr3:178952085 A > G
DX202629_01 chr2:25240315 G>T             | chr2:25463184 G>T
DX207760_01 chr17:7674220 C>T | 
DX208156_01 chr11:108284303 ->T           | chr11:108155030 ->T
DX208986_01 chr17:7674262                 | chr17:7577580 T>C
DX2103796_01 chr17:7675095 C>T            | chr17:7578413 C>T
DX2106763 chr19:1226580 A > G             | chr19:1226579 A > G

not called in gsvar file:
lifted positions - hg38 | old position - hg19
----|----
DX171568/DX2108845/DX2108847 chr10:86192503  | chr10:87952260 G>A
DX2108704_02/DX2108705_02 chr7:153155155 G>A | chr7:152852240 G>A



DX2108980_01 chr11:108365360 G>A no hg38 GSvar file

**Comment by Ott-Alexander** [comment]
Additional Controls:
DX171568_02 (1%) and DX173692_01 (7%): chr10:87952260 G>A
