### ISSUE TITLE
Add generic way to document causal variants that are not small variant, CNVs or SVs.

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#115]
add new table "report_configuration_other_causal_variant" with generic cause:
- id
- report_config_id
- coordinates (text)
- gene (text)
- type (enum[RE, UPD, mosaic CNV, uncalled small variant, uncalled CNV, uncalled SV])
- comment (text)

other changes:
- Add it to report config summary (processed sample tab, sample search, NGSDExportSamples, ...)
- Add it to report (HTML, XML)

**Comment by leonschuetz** [comment]
implemented in commit 9b657be05ddf5c8bdb77b905e2c53c80ed889df7
