### ISSUE TITLE
Missing "Data Types" file

### ISSUE THREAD

**Issue by apeltzer** [imgag/megSAP#12]
Unfortunately, the pipeline can't find the ".data_types" file in annotation now. However, the data was downloaded properly and without any errors and looks sane to me (when manually checking). All other reference genome / panel data is also present and used properly. 

    2017-10-26T12:49:42.7095        Qqrz        Exception in thread "main" java.lang.RuntimeException: 
    java.lang.RuntimeException: java.io.FileNotFoundException: 
    /megSAP/data/dbs/dbNSFP/dbNSFPv2.9.3.txt.gz.data_types (Permission denied)

**Comment by imgag** [comment]
Hi Alexander,

is the file there?
If so, are the the permissions ok?
The error message says "Permission denied"...

Best,
  Marc

**Comment by apeltzer** [comment]
Hi Marc,

no, the file was apparently not created / downloaded. Permissions to files are okay, everything else in the directory can be used properly.

**Comment by apeltzer** [comment]
Downloading the file (~7hours). I'll keep you posted.

**Comment by apeltzer** [comment]
So after checking the file content, the `gz.data_types` seems not to be there anymore. 

    [iiipe01@u-003-ncmu03 ~]$ unzip -l dbNSFPv2.9.3.zip 
    Archive:  dbNSFPv2.9.3.zip
     Length      Date    Time    Name
    ---------  ---------- -----   ----
     46814  03-12-2017 16:20   dbNSFP2.9.3.readme.txt
    9403906725  03-15-2017 08:38   dbNSFP2.9.3_variant.chr1
    3705105071  03-15-2017 08:50   dbNSFP2.9.3_variant.chr10
    5443692630  03-15-2017 09:04   dbNSFP2.9.3_variant.chr11
    4999107372  03-15-2017 09:17   dbNSFP2.9.3_variant.chr12
    1616606426  03-15-2017 09:20   dbNSFP2.9.3_variant.chr13
    3015005426  03-15-2017 09:26   dbNSFP2.9.3_variant.chr14
    2931499181  03-15-2017 09:32   dbNSFP2.9.3_variant.chr15
    3604269162  03-15-2017 09:40   dbNSFP2.9.3_variant.chr16
    4937581249  03-15-2017 09:50   dbNSFP2.9.3_variant.chr17
    1341514007  03-15-2017 09:52   dbNSFP2.9.3_variant.chr18
    5536933392  03-15-2017 10:03   dbNSFP2.9.3_variant.chr19
    6921005904  03-15-2017 10:22   dbNSFP2.9.3_variant.chr2
    2201457379  03-15-2017 10:27   dbNSFP2.9.3_variant.chr20
    951454124  03-15-2017 10:28   dbNSFP2.9.3_variant.chr21
    1979389394  03-15-2017 10:33   dbNSFP2.9.3_variant.chr22
    5491608245  03-15-2017 10:45   dbNSFP2.9.3_variant.chr3
    3772624783  03-15-2017 10:53   dbNSFP2.9.3_variant.chr4
    4228857991  03-15-2017 11:02   dbNSFP2.9.3_variant.chr5
    4722405602  03-15-2017 11:11   dbNSFP2.9.3_variant.chr6
    4281853798  03-15-2017 11:21   dbNSFP2.9.3_variant.chr7
    3190071955  03-15-2017 11:28   dbNSFP2.9.3_variant.chr8
    3787029495  03-15-2017 11:36   dbNSFP2.9.3_variant.chr9
    3275930225  03-15-2017 11:43   dbNSFP2.9.3_variant.chrX
     23691947  03-15-2017 11:43   dbNSFP2.9.3_variant.chrY
     31281799  12-16-2014 10:15   dbNSFP2.9_gene
     43105732  12-16-2014 10:15   dbNSFP2.9_gene.complete
     3189  05-31-2013 15:14   LICENSE.txt
    23692  03-12-2017 01:30   search_dbNSFP293.class
    35084  03-12-2017 01:30   search_dbNSFP293.java
    151154  03-12-2017 18:25   search_dbNSFP293.readme.pdf
     5954  11-30-2016 13:23   try.vcf
      254  03-20-2016 11:21   tryhg18.in
      256  04-12-2015 18:00   tryhg19.in
      254  04-12-2015 18:02   tryhg38.in
    ---------                     -------
    91437255665                     35 files

**Comment by imgag** [comment]
Hi Alexander,

I looked into the SnpSift documentation and it mentions the .gz and .gz.tbi file ones. 
This, I just tested what happens when I delete the data_types file and run it.
The file is created by SnpSift.

I guess you have to mount the folder writable in your container.
Perhaps only once is enough to allow writing the file.

The issue can be closed then, right?

Best,
  Marc

**Comment by apeltzer** [comment]
Ah, I guess that could be the reason. Since we want to enforce that nobody changes the data, we'd need to have it running once and then set everything to read only.

**Comment by apeltzer** [comment]
Yes, I guess this can be closed then.
