### ISSUE TITLE
Authorization problem when starting megSAP docker container

### ISSUE THREAD

**Issue by hofmannw** [imgag/megSAP#13]
Hello,
when I' m starting megSAP as a docker container I get a error message:
docker run --workdir /WORKDIR -v VOLUME:/data registry.gitlab.com/clinicalreporting/megsap_containerized /megSAP/data/download_hg19.sh /data
Unable to find image 'registry.gitlab.com/clinicalreporting/megsap_containerized:latest' locally
docker: Error response from daemon: Get https://registry.gitlab.com/v2/clinicalreporting/megsap_containerized/manifests/latest: denied: access forbidden.
It looks like a autorization problem.
Kind Regards, Winfried

**Comment by imgag** [comment]
Hi Winfried,

Bilge updated the instructions how to use that docker version:
https://github.com/imgag/megSAP_containerized
She thinks that you probably used the old instructions.

If the problem persists, can you please open an issue in the docker project:
https://github.com/imgag/megSAP_containerized

Thanks,
  Marc
