### ISSUE TITLE
Use DRAGEN for somatic variant calling

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#156]
- [x] implement tumor-normal variant calling with DRAGEN
- [x] document for accreditation
- [ ] Also implent tumor-only calling with DRAGEN?!
- [x] Also add somatic SV calling with dragen?
- [x] test for enzymatic fragmentation artefacts in DNA2300433A1_01-DNA2209669A1_01
     - Dragen also calls the artifacts as variants (sight check)

- [x] Check if it handles MNP correcly and calls them together (ex. DNA2300985A1_01 BRAF AC -> TT)
     - Dragen also calls two variants but provides phasing information.
     -  [] merge the two calls into one MNP (right next to each other or up to 6 bases apart)
---------
command line we got from Illumina two years ago:

dragen -r /staging/human/reference/GRCh37/GRCH37.fa.k_21.f_16.m_149/ --output-directory Sample_Horizon_01/ --tumor-fastq1 Sample_Horizon_01/Horizon_01_S14_R1_001.fastq.gz --tumor-fastq2 Sample_Horizon_01/Horizon_01_S14_R2_001.fastq.gz --enable-variant-caller true --vc-reference /NGS_Daten_Test/ngs-bits/data/genomes/GRCh37.fa --vc-target-bed /NGS_Daten_Test/Manifest/NGSD/idt_hog_pgen_complete_sorted_merged_20_annotated.bed  --vc-enable-depth-of-coverage true --enable-duplicate-marking true --enable-map-align-output true --enable-bam-indexing true --output-file-prefix somatic_Horizon_01 --RGID-tumor Horizon_01 --RGSM-tumor SM0-Horizon

---------
In case we don't switch:
check:
https://github.com/Illumina/strelka/blob/v2.9.x/docs/userGuide/README.md#improving-runtime-for-references-with-many-short-contigs-such-as-grch38
for runtime improvement of strelka2

**Comment by Ott-Alexander** [comment]
- [ ] check resulting GSvar file from dragen vs strelka GSvar file for shared variants
    - see folders: somatic_pipeline_test_dragen vs somatic_pipeline_test_strelka
- [ ] check umivar skript - select_monitoring_variants.py for dragen vcf-format. It can currently only read strelka vcfs. (checks for format field "GU")
- [ ] complete run through of the dragen pipeline version

**Comment by Ott-Alexander** [comment]
tumor-only implementation moved to its own issue
