### ISSUE TITLE
umiVar: improve settings handling

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#185]
umiVar settings.ini is inconvenient when installing megSAP.

Possible solutions:
- hand over settings file when running umiVar
- take settings from environment variables

ToDo:
- [x] implement one of the solutions
- [x] update megSAP accordingly

**Comment by leonschuetz** [comment]
Implemented in umiVar2 and megSAP in c565aab65ce6f950d3b803d284f8bab52e038b46
