### ISSUE TITLE
megSAP update

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#186]
Update tools and databases for megSAP
- germline (Marc)
  - [x] databases
    - [x] import into production NGSD 
  - [x] tools
  - [x] updated settings.ini.default and settings_nightly.ini
  - [x] update update_overview.md and pipeline-specific docu
- somatic (Alexander)
  - [x] databases
  - [x] tools 
  - [x] updated settings.ini.default and settings_nightly.ini
  - [x] update update_overview.md and pipeline-specific docu
- RNA (Jakob)
  - [x] databases
  - [x] tools 
  - [x] updated settings.ini.default and settings_nightly.ini
  - [x] update update_overview.md and pipeline-specific docu
- cfDNA (Leon)
  - [x] databases
  - [x] tools 
  - [x] updated settings.ini.default and settings_nightly.ini
  - [x] update update_overview.md and pipeline-specific docu
- [x] Update changeLog when everything is done (Marc)

**Comment by leonschuetz** [comment]
updated docu in fa50c5f3e8c8927d31849c049fbd3f814e8456d5 (no update needed)
