### ISSUE TITLE
LongReads: Implement methylation

### ISSUE THREAD

**Issue by leonschuetz** [imgag/megSAP#191]
example: https://pubmed.ncbi.nlm.nih.gov/37081487/
[pycoMeth: a toolbox for differential methylation testing from Nanopore methylation calls]( https://pubmed.ncbi.nlm.nih.gov/37081487/)

**Comment by leonschuetz** [comment]
- [ ] waiting for methylation info for the samples

**Comment by leonschuetz** [comment]
Tool for annotation:
[ZipperBams](http://fulcrumgenomics.github.io/fgbio/tools/latest/ZipperBams.html)

- steps new analysis:

   `unaligned BAM --> FastQ --> minimap --> ZipperBams --> sort (-->del unaligned BAM + Fastq)`

- steps reanalysis:

   `BAM --> FastQ --> minimap --> ZipperBams --> sort (-->del BAM + Fastq)`

**Comment by leonschuetz** [comment]
On hold till Nvidia-Benchmark

**Comment by leonschuetz** [comment]
new Dorado version creates mapped BAM with methylation

- [ ] adapt pipeline to use this BAM as input

**Comment by ubuntolog** [comment]
remapping with dorado

**Comment by leonschuetz** [comment]
https://github.com/lh3/minimap2/issues/977

Did anybody tested this?
Seems to solve the (re-)mapping issues with methylation.

@jakobmatthes @caspargross

**Comment by leonschuetz** [comment]
implemented in Branch [lr_methylation](https://github.com/imgag/megSAP/tree/lr_methylation)

- [ ] waiting for tests from @jakobmatthes

**Comment by caspargross** [comment]
Started test in `/mnt/storage1/projects/research/23064_1267_MSS_ONT`

**Comment by caspargross** [comment]
![image](https://github.com/imgag/megSAP/assets/10211013/159a4bc3-c00c-4831-b17c-df19fbe7a676)

Everything works! Phasing of known imprinted gene (SNRPN) is correct.

**Comment by leonschuetz** [comment]
- [ ] create pipeline test from unmod BAM

**Comment by leonschuetz** [comment]
- [ ] implement megSAP tool
- [ ] ingegrate into the pipeline
- [ ] add tests

**Comment by leonschuetz** [comment]
- [ ] search for list of common methylation regions
- [ ] search for tool to analyze methylation patterns
- [ ] methylation in NGSD? --> integratein in GSVar

**Comment by leonschuetz** [comment]
- [x] Add tool to extract methylation from modkit calls -> `ExtractMethylationData`

**Comment by leonschuetz** [comment]
- [ ] implement branch from Jakob 6852742d048c62298feb8af614d718521e2797c4
- [ ] add tools/container
- [ ] implement in GSvar
