### ISSUE TITLE
Keep error logs after execution

### ISSUE THREAD

**Issue by Fohlen** [imgag/megSAP#21]
As @jakobmatthes noticed it might be valuable to not discard the error log on failure. 
It is currently being discarded because the `tmpDir` will be deleted after pipeline execution.

**Comment by Fohlen** [comment]
@marc-sturm fixed this, didn't you? Can be closed?

**Comment by marc-sturm** [comment]
Fixed with ac33f172e0e24ce3c1c3375cacb8e96620e2fee9
