### ISSUE TITLE
Implement trio/multi

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#221]

**Comment by leonschuetz** [comment]
Sniffles has trio mode: [link](https://github.com/fritzsedlazeck/Sniffles#b-multi-sample-sv-calling-trios-populations)

- [ ] implement 
- [ ] adapt annotation
- [ ] test

**Comment by leonschuetz** [comment]
Clair3 has a trio version: [Clair3-Trio](https://github.com/HKU-BAL/Clair3-Trio)
- [ ] test
- [ ] implement

**Comment by leonschuetz** [comment]
test data: 
    - `S:\projects\research\21073N_SEQ418081722_trio\Sample_21073LRa013` - `Sample_21073LRa015`

**Comment by leonschuetz** [comment]
Clair3 first results:
 - takes very long (aborted after 5 Days with 4 threads)
 - very high memory usage
 - [ ] test new version with memory leak fix (not available via docker yet)

**Comment by leonschuetz** [comment]
Test with GATK combineGVCF

**Comment by leonschuetz** [comment]
First test seems to work:
 - [x] implement php script to use
 - [x] add genotype calling
 - [x] add post-processing
 - [x] add multithreading
 - [ ] implement in pipeline

**Comment by leonschuetz** [comment]
- [ ] implement pipline tests
    - [ ] trio
    - [ ] multi
- [ ] validate
- [ ] integrate in GSvar

**Comment by leonschuetz** [comment]
- [ ] fix bug in `merge_gvcf.php`
