### ISSUE TITLE
Kasp check error message could not find bam file

### ISSUE THREAD

**Issue by schmidgu** [imgag/megSAP#23]
Hi Marc,

due to changes in aour routine kasp check process we have the problem that samples are already documented in the ngsd but are not seuqneced yet. Therofore we got the follwing error masseage when we start the kasp_check.php script:

'ERROR: 'Could not find BAM file for sample NA12877!' in /megSAP/src/Tools/kasp_check.php:320.
Traceback:  trigger_error called at /megSAP/src/Tools/kasp_check.php:320
END kasp_check'

Would it be possible to change the script, so that the samples with no corresponding bam files are just skipped?

Best
Gunnar

**Comment by marc-sturm** [comment]
Done with 40ff6d9d0780654bd6239f37e2e41206dc9e41c1
