### ISSUE TITLE
IGV: use JSON genome definition

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#231]
- [x] check if NGSDExportGff can be used (after [#499](https://github.com/imgag/ngs-bits/issues/499) is fixed)
- [x] move from separate repo to megSAP 
- [ ] use as default for IGV

**Comment by leonschuetz** [comment]
- [ ] test and integrate in GSvar

**Comment by marc-sturm** [comment]
NGSD updated > re-export GFF and create test version of GSVar!

**Comment by marc-sturm** [comment]
- [ ] Shows RNA in header
- [ ] shows all CDS/UTR exons > should not
- [ ] does not show Exon and AA number
- [ ] show mane in extra track: https://hgdownload.soe.ucsc.edu/gbdb/hg38/mane/mane.bb
- [ ] show ENST and NM number(s) if available

**Comment by leonschuetz** [comment]
RefSeq format: https://genome.ucsc.edu/cgi-bin/hgTables

**Comment by leonschuetz** [comment]
implemented in ngs-bits tool NGSDExportIgvGeneTrack a8d519bb7b6a9438906ddf1b577d265259c95f58 using the refgene format
