### ISSUE TITLE
Invalid INFO header in annotated Longread VCF

### ISSUE THREAD

**Issue by caspargross** [imgag/megSAP#234]
In einigen (weiss nicht ob allen) VCFs aus der LongRead pipeline ist ein leeres INFO field im Header:

```
> zcat /mnt/storage1/projects/research/22018I_0947_SCA4/Sample_22018LRa055_01/22018LRa055_01_var_annotated.vcf.gz | grep 'ID=,' 
##INFO=<ID=,Number=1,Type=String,Description="no description available">
```

Das führt zu einem Fehler in beispielsweise `vcftools` 
Läuft der VCFCheck nicht automatisch in der annotation Pipeline?

**Comment by leonschuetz** [comment]
Hab es gerade gecheckt. `an_vep.php` macht einen `VCFCheck`, aber nur die ersten 1000 Zeilen und unser header ist mittlerweile größer. Die falsche header line ist allerdings schon im `_var.vcf.gz`, ich versteh aber noch nicht, woher die kommt.
