### ISSUE TITLE
Re-calculation of *.cov files after re-mapping

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#241]
Hi,
Currently you check if the .cov file for the CNV-analysis is already present and don't re-calculate it 
[`if (!file_exists($cov_file))`](https://github.com/imgag/megSAP/blob/ec9bf63d58f83fc649606b7dd68437106f7376a2/src/Pipelines/analyze.php#L762C1-L762C31)

We recently had a sample mix-up and forgot to delete the corresponding .cov-files. Thus the CNVs were of the wrong sample.
Would it be possible to re-calculate the cov-files when a new mapping was performed, thus changing the above linked line to this:

`if (!file_exists($cov_file) OR in_array("ma", $steps))`

Thus a new mapping would lead to a new cov-file and would prevent further problems downstream

Thank you

Alex

**Comment by marc-sturm** [comment]
Fixed in https://github.com/imgag/megSAP/commit/ed6ee2eb40936d3673cbb23e48aa23475de8a747
