### ISSUE TITLE
download_dbs.sh throws exception: Reference sequence of variant ... does not match reference bases in genome ...

### ISSUE THREAD

**Issue by leonid-iashin2** [imgag/megSAP#244]
Thank you very much for this repository!

I am installing it from scratch for the first time (from the master branch). Currently, I am stuck on `download_dbs.sh` throwing an exception:

> VcfLeftNormalize 2023_11
> Exception: Reference sequence of variant (chr9:70701809 A>G) does not match reference bases in the genome (N).
> Location: ../../src/cppNGS/VcfLine.cpp:477

I have traced this exception to the `ngsbits` repository and discovered that the master branch has a recent commit ([VcfLeftNormalize: now skips invalid variants](https://github.com/imgag/ngs-bits/commit/1e6019aad81976f1ecc01486e6e365b2be2c2862)) after the 2023_11 release. I believe this commit is necessary for me to proceed. Are there any known issues between the `megSAP` master branch and the `ngsbits` master branch?

On to another, even more important question: can `download_dbs.sh` continue downloading if I comment out all relevant commands before `chr9`? Or should I delete `./dbs/gnomAD/gnomAD_genome_v3.1.2_GRCh38.vcf` and restart `download_dbs.sh` completely? It takes more than a day to finish for me, and I have already done a couple of restarts, so I was hoping to save some time.

**Comment by marc-sturm** [comment]
Yes, please use the master of ngs-bits.
It should work without any problems.

You should be able to continue with the chr9.

**Comment by leonid-iashin2** [comment]
Thank you very much for quick response. 
I have continued with chr9 as agreed yesterday, but alas, today I got the following exception from tabix 
>tabix -C -m 9 -p vcf gnomAD_genome_v3.1.2_GRCh38.vcf.gz
>[E::hts_idx_push] Unsorted positions on sequence #9: 70701796 followed by 10047
>tbx_index_build failed: gnomAD_genome_v3.1.2_GRCh38.vcf.gz

seems like I did something wrong, or continuing was not possible? I think the only option now is to restart the whole process (or?). But still, out of curiosity, when we were talking about continuing with chr9, did you also mean it like in this file?:
[download_dbs_fromchr9.sh.txt](https://github.com/imgag/megSAP/files/14138165/download_dbs_fromchr9.sh.txt)

**Comment by marc-sturm** [comment]
Yes, the modification of the script is how I meant it.
Now that I see it it is however clear that this cannot work.
Part of the chr9 data is already in the file. When you add the chr9 data to that the tabix error is clear.

You could remove all lines starting with "chr9" e.g. using egrep.
Then It should work.

Or you just restart the gnomAD download from chr.1

**Comment by leonid-iashin2** [comment]
Sounds intriguing!
So e.g. now I could:
`bgzip -d gnomAD_genome_v3.1.2_GRCh38.vcf`
`grep -v '^chr9' gnomAD_genome_v3.1.2_GRCh38.vcf > gnomAD_genome_v3.1.2_GRCh38_nochr9.vcf`
and then:
`wget -O - https://storage.googleapis.com/gcp-public-data--gnomad/release/3.1.2/vcf/genomes/gnomad.genomes.v3.1.2.sites.chr9.vcf.bgz | gunzip | $ngsbits/VcfLeftNormalize -stream -ref $genome | $ngsbits/VcfStreamSort | php $src/Tools/db_converter_gnomad.php >> gnomAD_genome_v3.1.2_GRCh38_nochr9.vcf`
And it would be okay then to compress with bgzip & run tabix even if chr9 is in the end? Or should they be ordered in the vcf file, meaning I have to also delete chr10-chrY and restart them together with chr9?

**Comment by marc-sturm** [comment]
You should delete all chromosomes after chr8 and restart again.
