### ISSUE TITLE
Longread vc_clair python environments problems

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#251]
Hi,
we tried the longread pipeline for the first time and had some problems with the python environments.

First, the file `install_deps_python_clair3.txt` does not seem to be called in the installation anywhere.

Additionally, all of the long-reads tools point towards the `[path]/data/tools/Python-3.10.9` directory, while the tools are actually installed in the `[path]/data/tools/Python-3.10.9_8.2.24` directory

The same is true for the python-environment when using Clair. I had to add the entry `clair3_python = [path]/data/tools/Python-3.10.9_8.2.24/bin/python` in the settings.ini and then use that as the python environment for Clair.

Maybe you can update that or adapt the installation scripts to use the `[path]/data/tools/Python-3.10.9` directory

Furthermore, the versions/paths for `clair3`, `clair3_models` and `pypy3` need to be updated in the `settings.ini.default`

Best,
Alex

**Comment by leonschuetz** [comment]
Hi,

thank you for the info.
The file `install_deps_python_clair3.txt` isn't used anymore and was merged into `install_deps_python.txt` and is now removed.
The python installation at `[path]/data/tools/Python-3.10.9` is only used to create the venv, all tools and packages are installed in the venv with date suffix. I updated the paths in the `settings.ini.default`.

Best,
Leon

**Comment by alex-seitz** [comment]
Hi,
thank you for your quick response.
Thhe only thing left is the python environment for vc_clair. In line 50 in the src/NGS/vc_clair.pph the python3 environment ist used. However, all of the libraries are installed into the venv and thus not available in the "normal" installation (My problem was the module `tensorflow`), which is why I had to add a new path to the python venv and include it at that position

**Comment by leonschuetz** [comment]
Hi,
the `python3` setting should also point to the venv (with date suffix) and all megSAP tools should only use this common environment.

Best,
Leon

**Comment by alex-seitz** [comment]
Ok, thank you for explaining it. I will adapt it as you said
