### ISSUE TITLE
No QC when using CRAM

### ISSUE THREAD

**Issue by BeneKenobi** [imgag/megSAP#256]
Hi,

do I understand it correctly that the `ma` step only creates ReadQC/MappingQC for already mapped/called samples from the NovaSeq X if a BAM-file is the input as seen from here :
https://github.com/imgag/megSAP/blob/bee565ce3750977222cf74d64270a9eb8fd3a52a/src/Pipelines/analyze.php#L318 

and just continues if a CRAM is used (starting here):
https://github.com/imgag/megSAP/blob/bee565ce3750977222cf74d64270a9eb8fd3a52a/src/Pipelines/analyze.php#L370

?

As @marc-sturm suggested we only produce CRAM files with the NovaSeq X now. Don't we need this QC stuff though?

**Comment by marc-sturm** [comment]
This is a bug.

It is fixed in https://github.com/imgag/megSAP/commit/fc75ab82061c84cc61e5ae5e32a754b37bddb8f7
