### ISSUE TITLE
Getting problem when I type "./download_dbs.sh"

### ISSUE THREAD

**Issue by ThomasYang0615** [imgag/megSAP#266]
Hello,
I have problem at the final step of installing megSAP : ```./download_dbs.sh```

When I execute '''download_dbs.sh''' :
- I can't Install CancerHotspots.org, the address of row 25 seems broken
    - wget https://www.cancerhotspots.org/files/hotspots_v2.xls
- I can't Install ClinVar, there will be ERROR: 
    - Error in get_ref_seq : Failed to open the file /tmp/local_ngs_data//GRCh38.fa 
    - [faidx] Could not build fai index /tmp/local_ngs_data//GRCh38.fa.fai

I did try to find out the solution, but I stuck.
Can you give me a hand?

**Comment by noob9721** [comment]
Hello,
Did you get a solution for this by any chance? I have the same problem.

**Comment by marc-sturm** [comment]
Which version of megSAP are u using?
2023_11 or the master?

CancerHotspots:
the URL should work when using the master

Clinvar:
please use the latest master, I just comitted a fix, see 3e253ccda9f9a4fb5a5fd004fc4337d5a09975da

Does it work with the master?

**Comment by marc-sturm** [comment]
The error is not fixed in version 2024-09.
The error is fixed in the master only.

**Comment by JiangyanYu** [comment]
The file db_converter_clinvar.php from 2024_09 actually has the changed command line:
	//prepend padding base for complex variants
	if ((strlen($ref)>1 || strlen($alt)>1) && strlen($ref)!=strlen($alt) && $ref[0]!=$alt[0])
	{
		$pos -= 1;
		$base = get_ref_seq("GRCh38", $chr, $pos, $pos, false);
		$ref = $base.$ref;
		$alt = $base.$alt;
	}

However, the same error still occurs. 

Or you have updated other files too? Thanks a lot!

**Comment by marc-sturm** [comment]
Please change it to:
get_ref_seq("GRCh38", $chr, $pos, $pos, 0, false);

Then it should work

**Comment by JiangyanYu** [comment]
it works now! thanks!

Jiangyan
