### ISSUE TITLE
RefSeq Annotation

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#268]
Hi,
I know you removed the VEP refSeq annotation, probably due to time constraints. However we still need it and it would be great if you could include it as an optional annotation in `an_vep.php`.
The simple matching between ENST and NM using MANE is not enough, because often we need Transcripts for which an exact match is not available, as well as the correct HGVS nomenclature to compare with databases like HGMD (not exact matches, but variants at the same c- or p-position).
Thank you
Alex

**Comment by marc-sturm** [comment]
I will add it as an optional step again

**Comment by alex-seitz** [comment]
Thank you

**Comment by marc-sturm** [comment]
VcfAnnotateConsequence updated:
https://github.com/imgag/ngs-bits/commit/f7817d30ba739c4b5ea2f092b830b5cdc760617a

**Comment by marc-sturm** [comment]
megSAP changes:
https://github.com/imgag/megSAP/commit/84fb483efc0dbf8aa01d59aca3d4f2104fcc7488
