### ISSUE TITLE
CNV burden

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#29]
Calculte CNV burden and show it in GSvar/report.

CNV burden: percentage of ROI that is affected by CNVs

**Comment by marc-sturm** [comment]
Here the paper:
https://elifesciences.org/articles/37294

**Comment by axelgschwind** [comment]
I have added the calculation of the CNV burden to GSvar (instead of megSAP). It is better to have it in GSvar because the clinicians remove false positives manually just before they create a somatic report.
