### ISSUE TITLE
Possible bug ?

### ISSUE THREAD

**Issue by colindaven** [imgag/megSAP#3]
Hi,

think I found a bug in download_dbs.sh

`#Install REPEATMASKER`

`perl $dbs/tools/RepeatMasker/util/rmOutToGFF3.pl hg19.fa.out > RepeatMasker.gff` 

should go up directory before going into the tools directory, added "../"

`perl $dbs/../tools/RepeatMasker/util/rmOutToGFF3.pl hg19.fa.out > RepeatMasker.gff`

**Comment by imgag** [comment]
Hi Colin,

yes, the path was wrong.
I replaced $dbs/tools by \`pwd\`/tools, which should fix the problem.

Best,
  Marc
