### ISSUE TITLE
download_dbs.sh error

### ISSUE THREAD

**Issue by zxmmx04** [imgag/megSAP#30]
In commit "fb1d6f512c36ae2e9d4130b023982f001c425a75" you added the file "somatic_tmb_tsg.bed" into the data/dbs/NCG6.0 directory
Thus the download_dbs.sh will want to create this directory but then breaks as it already exists after cloning from github.
Please change
mkdir NCG6.0
in line 16 of the download_dbs.sh
mkdir -p NCG6.0
in order to make it work again

Best,
Alex

**Comment by axelgschwind** [comment]
Hi Alex,

the file was accidentially commited which was fixed by Marc a few minutes ago :). In the latest commit, this should not happen again.
Thank you very much for reporting this.

Best,

Axel
