### ISSUE TITLE
megSAP data download error

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#302]
`db_converter_ncg.php` called in `download_dbs.sh` uses ng-bits tool `GenesToBed`, but this tool needs the NGSD.

Error message:
```
#Install NCG7.1 - information about oncogenes and tumor suppressor genes
cd $dbs
mkdir -p NCG7.1
cd NCG7.1
curl 'http://network-cancer-genes.org/download.php' --silent -X POST --data-raw 'downloadcancergenes=Download' | sed -e "1s/^/#/" > ncg.tsv
php $src/Tools/db_converter_ncg.php -in ncg.tsv -prefix NCG7.1 -outfolder "."
GenesToBed 2024_08
Programming exception: Requested key 'ngsd_host' not found in settings!
Location             : ../../src/cppCORE/Settings.cpp:252
This should not happen, please report the error to the developers!
ERROR: 'Call of 'Generate tsg bed file.' pipeline returned error code '1'.' in /mnt/NFS/s-msp01/fbz_megsap_app/apps/megSAP/src/Common/ToolBase.php:819.
```

**Comment by marc-sturm** [comment]
What did you clone?
Version 2024_09?
The error is fixed on the master only:
https://github.com/imgag/megSAP/commit/917f370e36cc0250d5abb56632ea93b8928be0d8#diff-1af7169e9cd069d6b6df22adce940191c2fd08e7d54e2aab9a813f79cfa1f97cL79

**Comment by JiangyanYu** [comment]
Thanks for the quick reply! Yes, I cloned 2024_09. I adjusted the corresponding files as stated in the master file. Now the problem is solved.

Thanks!
