### ISSUE TITLE
db_converter_repeatmasker not working

### ISSUE THREAD

**Issue by zxmmx04** [imgag/megSAP#31]
Hello,
the db_converter_repeatmasker.php is not working, it can't find the function fopen2

It appears the import of the functions is missing in this script.
the db_converter_omim has the following line, which is not present here:
require_once(dirname($_SERVER['SCRIPT_FILENAME'])."/../Common/all.php");

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for reporting this and your correct analysis.

I fixed it in commit 2ac5d5807918903f6f5e9d4dabb3f66b13e36ca7.

I also just finalized the quaterly update of tools/databases the the commit before.
If you just started installing megSAP, you should perhaps use the latest version instead.

Best,
  Marc
