### ISSUE TITLE
Installing: HGNC link not found

### ISSUE THREAD

**Issue by JiangyanYu** [imgag/megSAP#311]
Dear megSAP team,

I had an issue for HGNC (see following error). I guess it is due to the name change of the folder in their website. It shall be:
https://ftp.ebi.ac.uk/pub/databases/genenames/out_of_date_hgnc/tsv/

wget -O - http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt > hgnc_complete_set.tsv
--2024-11-18 14:22:32--  http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-11-18 14:22:32 ERROR 404: Not Found.

Best, Jiangyan

**Comment by marc-sturm** [comment]
This is fixed in the master already:
https://github.com/imgag/megSAP/blob/master/data/download_dbs.sh#L73-L78
