### ISSUE TITLE
Problem with Freebayes on WGS with empty target_file

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#33]
Hey,
when running a WGS analysis and specifying an empty target_file:
`target_file = ""`
Freebayes won't start running and there is no error message.
The problem appears to be the check for mitochondrial analyses in line 160 of the analyze.php:
`$only_mito_in_target_region = exec2("cat ".$sys['target_file']." | cut -f1 | uniq")[0][0] == "chrMT";`
As there is no check if the `target_file` is empty and thus there appears to be a problem with the error of printing a nonexistant file.
first initializing the variable with `false`and then checking if the `target_file`is not empty appears to solve the problem
Code:
`$only_mito_in_target_region = false;`
`if ($sys['target_file']!="")`
`{`
`//Do not call standard pipeline if there is only mitochondiral chrMT in target region`
`$only_mito_in_target_region = exec2("cat ".$sys['target_file']." | cut -f1 | uniq")[0][0] == "chrMT";`
`}`

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for reporting this and providing the solution.
It's fixed in e6bb2876bc407f3a9f80e9131b22028fdbb4678a

Best,
  Marc
