### ISSUE TITLE
Installation discrepancies

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#34]
Hey,
I just realized that manta, which is needed for the analysis of structural variants, is not installed. The installation of manta is done in the `download_tools_somatic.sh`. Is there a reason for this? Is it not advised to do analyses of structural variation on "normal" samples (even if the possibility (`-steps sv` is there)?

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for reporting this.
It's fixed in e6bb2876bc407f3a9f80e9131b22028fdbb4678a

Best,
  Marc
