### ISSUE TITLE
Discrepancies in settings.ini

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#35]
Hey,
in the download_tools.sh, you download the delly executable directly into the tools directory. However, in the settings.ini, the path contains an additional subdirectory.
Additionally, you download manta 1.5.0, whereas in the settings.ini, the path still points to 1.4.0

Best,
Alex

**Comment by marc-sturm** [comment]
Delly path is fixed in 13fb54e08e9768e5ae67ae7c79f8c6a8eb24e94a

**Comment by marc-sturm** [comment]
The manta version is now also correct: c21762fc420393c1b273fdae134fd6051fab9b45
