### ISSUE TITLE
runqc_parser requires interop

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#36]
Hello,
I wanted to try the runqc_parser but it fails with the error

`ERROR: 'Could not find key 'interop' in settings file '/opt/megSAP/settings.ini'!' in /opt/megSAP/src/Common/genomics.php:241.`

When I search for interop in the repository, the only place I can find it is the settings_nightly.ini. 
Can/Should I just download the interop executable from the github-project and refer to it in the settings.ini?

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks for reporting this.
I added installation instructions in 8c3e890fd8d454bfe525de877067c99e94956971.

Best,
  Marc
