### ISSUE TITLE
HGNC missing

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#37]
Hello again,
I realized, you removed the download of HGNC in the download_dbs.sh in Commit 134670f.
However, vcf2gsvar.php still requires this file in line 175.

Best,
Alex

**Comment by marc-sturm** [comment]
Hi Alex,

thanks, I thought it is not used and missed that.
Fixe in dfdbdf6a506311d6ae7adf399c0f947b99cf16df

Best,
  Marc
