### ISSUE TITLE
Installation Instructions missing/wrong dependencies

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#38]
Hey,
I just realized, that when you want to install the devtools for R, the following package has to be installed first:
`libcurl4-openssl-dev`

Additionally, in the `install_deps_clincnv.R`,
the line `install.packages("mass", repos="https://cran.rstudio.com")`
gives me the following error:
`Warning messages:`
`1: package ‘mass’ is not available (for R version 3.6.1) `
`2: Perhaps you meant ‘MASS’ ?`

Best,
Alex

**Comment by marc-sturm** [comment]
Thanks, should be fixed.
