### ISSUE TITLE
Error when running without NGSD annotation

### ISSUE THREAD

**Issue by alex-seitz** [imgag/megSAP#39]
Hey,
I tried the new version with a new database.
when trying to run the pipeline without the NGSD annotation files present, it terminates with the error:
`ERROR: 'Cannot get modification date of '/opt/megSAP//data//dbs/NGSD/NGSD_germline.vcf.gz'!' in /opt/megSAP/src/NGS/an_vep.php:328.`
After generating these files from the empty database without any entries, it worked.
Best,
Alex

**Comment by leonschuetz** [comment]
Hello Alex,
Should be fixed in commit 47d2183.
Best Regards,
Leon
