### ISSUE TITLE
Another bug

### ISSUE THREAD

**Issue by colindaven** [imgag/megSAP#4]
Hi Marc,

I think I found another bug in 

download_dbs.sh

In the dbSNP extraction string, the VcfLeftNormalize command requires a "-ref /path/to/hg19.fa" argument.

In my case
`zcat 00-All.vcf.gz | php $src/Tools/db_converter_dbsnp.php | $vcflib/vcfbreakmulti | $ngsbits/VcfLeftNormalize -ref /galaxy_nfs/tools/megsap/data/genomes/hg19.fa`

Thanks,
Colin

**Comment by imgag** [comment]
thanks again, I fixed all VcfLeftNormalize calls in the script.
