### ISSUE TITLE
wrong variable?

### ISSUE THREAD

**Issue by clsh-ldw** [imgag/megSAP#40]
Hi there!

shouldn't

https://github.com/imgag/megSAP/blob/cdfe852caa89516c5871706c422c02d89bae520d/src/NGS/vcf_fix.php#L111

be

$sample_last = sample_data($var_last[8], $var_last[9]);

???

**Comment by marc-sturm** [comment]
Thanks a lot for reporting this.
It's now fixed.
-Marc
