### ISSUE TITLE
update tools to current versions

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#43]
- update all tools used in megSAP the most recent version
- reactivate Genesplicer in VEP 100 (test if runtime is ok now - see https://github.com/Ensembl/ensembl-vep/issues/641)
- update freebayes to version 1.3.1  and https://github.com/imgag/megSAP/issues/42 (finds 2bp Deletion at X:38,145,608-38,145,647 in DX202065_02)

**Comment by marc-sturm** [comment]
Also try BWA-mem2: https://github.com/bwa-mem2/bwa-mem2/releases/tag/v2.0

**Comment by leonschuetz** [comment]
updated freebayes, VEP, samtools, samblaster and mantis in 493d11ff0b119343594ebf1bb574d83e171b89a0

**Comment by leonschuetz** [comment]
bwa-mem2 only usable if shared memory feature is implemented ([ #65](https://github.com/bwa-mem2/bwa-mem2/issues/65)).
Otherwise the memory requirements are too high (~50GB per analysis).
