### ISSUE TITLE
Use COSMIC as replacement for CGI

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#44]
1) Make a list of data do we use from CGI for SNVs, Indels and CNVs
2) Search for alternatives (ask Stephan, Sorin, Christioher)
  - Support GRCh37/GRCh38?
  - Downloadable and download data format ok (VCF)?
  - License of?
  - Cancer type as list/ontology? Convertable to other DBs?

TODO:
- metaKB: Use text search, filter for gene/protein change. Check post filtering to make sure variant is the same as requested.
- check license and exclude DB if not usable for commercial use.

**Comment by axelgschwind** [comment]
We decided for a COSMIC licence on 2019-09-16.
TODOs:
- annotate COSMIC data which should be able to replace CGI using the academic database downloads

**Comment by axelgschwind** [comment]
COSMIC data is annotated for VCF, however, this issue is put on hold because we need a proper COSMIC licence to continue development. This will be done by legal departments

**Comment by axelgschwind** [comment]
I have adapted the somatic RNA and DNA report to COSMIC and VICC classification.
Drugs from CGI are not printed into report because it is outdated.

CGI annotation for tumor-only report will stay in place (SNV only), because MHH does not have another classification system yet.
