### ISSUE TITLE
add PRS

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#48]
Add PRS to megSAP/GSvar:
- store a list of PRSs one VCF per PRS
  - meta data: name, cutoff, paper link
  - variants: left-normalized
- call for WGS at the end of the "vc" step and store as table
- show in GSvar 

Original text from Stephan:
- I make a list of suitable PRS. For now please use Breast Cancer PRS as template
- We need to automate the calculation in MegSAP. Simply compute the PRS formula with the SNVs you can find in WGS. Do not impute missing SNVs. PRS will only be used for WGS, not for WES.
- Generate a simple 1-page report listing all tested PRS in a table. If the patient is below a threshold we print "Normal". Above the threshold (e.g. odds ratio > 2) we show the odds ratio and the lifetime risk increase
- optional: For each increased PRS we provide a plot of the odds ratio population distribution (in-house individuals) as appendix 
- optional: a new window in GSvar showing the same PRS overview table (similar to CNV and SV window)

**Comment by leonschuetz** [comment]
implemented in b95cd3cc8ea55318aa639dcf85aa9013d8144aeb
