### ISSUE TITLE
test effect of strand bias filtering for WGS

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#49]
Test strand bias filtering for small variants in WGS:
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">

##INFO=<ID=SRP,Number=1,Type=Float,Description="Strand balance probability for the reference allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SRF and SRR given E(SRF/SRR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SAP,Number=A,Type=Float,Description="Strand balance probability for the alternate allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SAF and SAR given E(SAF/SAR) ~ 0.5, derived using Hoeffding's inequality">

Also test the effect of allele balance filtering:
##INFO=<ID=ABP,Number=A,Type=Float,Description="Allele balance probability at heterozygous sites: Phred-scaled upper-bounds estimate of the probability of observing the deviation between ABR and ABA given E(ABR/ABA) ~ 0.5, derived using Hoeffding's inequality">

**Comment by marc-sturm** [comment]
SAP and ABP are now added to the pipeline: 5523ffbd6751688f84ba00f7d174388d238ea42b

**Comment by marc-sturm** [comment]
Added allele balance and strand bias options to "variant quality" filter in GSvar:
https://github.com/imgag/ngs-bits/commit/9de01bb24d62bf13cbdc452685aa1b625f32e669

**Comment by marc-sturm** [comment]
@leonschuetz Maybe these filters can be used for automated re-analysis (test on causal/artefact variants)

**Comment by leonschuetz** [comment]
Removes a few variants, but not many.
