### ISSUE TITLE
not valid Miso term

### ISSUE THREAD

**Issue by colindaven** [imgag/megSAP#5]
Hi again, 

I have solved a lot more issues in the meantime checking paths to snpeff etc (probably due to the fact the download scripts didn't work that well for me due to my environment), but now have a problem I can't solve myself.

/galaxy_nfs/tools/megsap$ php megSAP/src/Pipelines/analyze.php -folder Sample_NA12878_01 -name NA12878_01 -system hpHBOCv5.ini -steps ma,vc,an

**ERROR: 'Invalid VCF-file. SnpEff effect 'non_coding_transcript_exon_variant' is not valid Miso term in '/tmp/annotate_AormvJ.vcf'.' in /galaxy_nfs/tools/megsap/megSAP/src/NGS/check_vcf.php:97.**
ERROR: 'Call of external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/NGS/check_vcf.php' returned error code '255'.' in /galaxy_nfs/tools/megsap/megSAP/src/Common/ToolBase.php:877.
ERROR: 'Call of external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/Pipelines/annotate.php' returned error code '255'.' in /galaxy_nfs/tools/megsap/megSAP/src/Common/ToolBase.php:877.

This is using the sample data. Any ideas ? I haven't run through successfully yet.

In the VCF this type of variant seems to happen a lot.

chr17   41245466        rs1799949       G       A       460.0   .       MQM=60;ANN=A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:Phosphoserine|NM_007300.3|protein_coding|10/24|c.2082C>T||||||,A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:phosphoserine|NM_007300.3|protein_coding|10/24|c.2082C>T||||||,A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:Phosphoserine|NM_007297.3|protein_coding|9/22|c.1941C>T||||||,A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:phosphoserine|NM_007297.3|protein_coding|9/22|c.1941C>T||||||,A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:Phosphoserine|NM_007294.3|protein_coding|10/23|c.2082C>T||||||,A|sequence_feature|MODERATE|BRCA1|BRCA1|modified-residue:phosphoserine|NM_007294.3|protein_coding|10/23|c.2082C>T||||||,A|synonymous_variant|LOW|BRCA1|BRCA1|transcript|NM_007300.3|protein_coding|10/24|c.2082C>T|p.Ser694Ser|2314/7270|2082/5655|694/1884||,A|synonymous_variant|LOW|BRCA1|BRCA1|transcript|NM_007297.3|protein_coding|9/22|c.1941C>T|p.Ser647Ser|2222/7115|1941/5451|647/1816||,A|synonymous_variant|LOW|BRCA1|BRCA1|transcript|NM_007294.3|protein_coding|10/23|c.2082C>T|p.Ser694Ser|2314/7207|2082/5592|694/1863||,A|intron_variant|MODIFIER|BRCA1|BRCA1|transcript|NM_007298.3|protein_coding|9/21|c.787+1295C>T||||||,A|intron_variant|MODIFIER|BRCA1|BRCA1|transcript|NM_007299.3|protein_coding|10/21|c.787+1295C>T||||||,A|**non_coding_transcript_exon_varian**t|MODIFIER|BRCA1|BRCA1|transcript|NR_027676.1|pseudogene|10/23|n.2218C>T||||||;KAVIAR_AF=0.3388080;T1000GP_AF=0.336462;EXAC_AC_Hom=7796;EXAC_AF=0.34826494260457;EXAC_Hom_AFR=286;EXAC_Hom_NFE=3607;CLINVAR_ACC=RCV000111763.4|RCV000114984.2|RCV000128966.3|RCV000152868.4;CLINVAR_SIG=benign|benign|benign|benign;COSMIC_ID=COSM3755567,COSM148280    GT:DP:AO        0/1:62:27

cheers,
Colin

**Comment by imgag** [comment]
Hi Colin,

the error occurs if the SnpEff version and the Miso Ontology are not compatible. 
Please try and update megSAP. 
That should fix your problem. I updated Miso on February 16th:
https://github.com/imgag/megSAP/tree/master/data/dbs/Ontologies

Best,
  Marc

**Comment by colindaven** [comment]
Thanks Marc. Unfortunately despite updating the Ontology and changing the relevant php script I get the next error:

php megSAP/src/Pipelines/analyze.php -folder Sample_NA12878_01 -name NA12878_01 -system hpHBOCv5.ini -steps ma,vc,an
**ERROR: 'Invalid VCF-file. SnpEff effect 'intron_variant' is not valid Miso term in '/tmp/annotate_fJsBzi.vcf'.**' in /galaxy_nfs/tools/megsap/megSAP/src/NGS/check_vcf.php:97.
ERROR: 'Call of external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/NGS/check_vcf.php' returned error code '255'.' in /galaxy_nfs/tools/megsap/megSAP/src/Common/ToolBase.php:877.
ERROR: 'Call of external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/Pipelines/annotate.php' returned error code '255'.' in /galaxy_nfs/tools/megsap/megSAP/src/Common/ToolBase.php:877.

Looking at the ontology I see te snpEff terms are all upper case, and intron_variant is not listed

grep snpEff megSAP/data/dbs/Ontologies/so-xp_3_0_0.obo  > x2.txt

        <td id="LC13647" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:GENE&quot; EXACT VAR []</td>
        <td id="LC13672" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:REGULATION&quot; EXACT VAR []</td>
        <td id="LC13685" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:NON_SYNONYMOUS_STOP&quot; EXACT VAR []</td>
        <td id="LC13686" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SYNONYMOUS_STOP&quot; EXACT VAR []</td>
        <td id="LC13743" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:EXON_DELETED&quot; EXACT VAR []</td>
        <td id="LC13766" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SPLICE_SITE_ACCEPTOR&quot; EXACT VAR []</td>
        <td id="LC13783" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SPLICE_SITE_DONOR&quot; EXACT VAR []</td>
        <td id="LC13799" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:TRANSCRIPT&quot; EXACT VAR []</td>
        <td id="LC13832" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:STOP_LOST&quot; EXACT VAR []</td>
        <td id="LC13865" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CDS&quot; EXACT VAR []</td>
        <td id="LC13866" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CODON_CHANGE&quot; RELATED VAR []</td>
        <td id="LC13886" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:NON_SYNONYMOUS_START&quot; RELATED VAR []</td>
        <td id="LC13909" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:NON_SYNONYMOUS_CODING&quot; EXACT VAR []</td>
        <td id="LC13960" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:STOP_GAINED&quot; EXACT VAR []</td>
        <td id="LC13989" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:FRAME_SHIFT&quot; EXACT VAR []</td>
        <td id="LC14301" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:MICRO_RNA&quot; EXACT VAR []</td>
        <td id="LC14344" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:UTR_5_PRIME&quot; EXACT VAR []</td>
        <td id="LC14366" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:UTR_3_PRIME&quot; EXACT VAR []</td>
        <td id="LC14405" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:INTRON&quot; EXACT VAR []</td>
        <td id="LC14425" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:INTERGENIC&quot; EXACT VAR []</td>
        <td id="LC14455" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SPLICE_SITE_BRANCH&quot; RELATED VAR []</td>
        <td id="LC14456" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SPLICE_SITE_BRANCH_U12&quot; RELATED VAR []</td>
        <td id="LC14457" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SPLICE_SITE_REGION&quot; EXACT VAR []</td>
        <td id="LC14474" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:UPSTREAM&quot; EXACT VAR []</td>
        <td id="LC14491" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:DOWNSTREAM&quot; EXACT VAR []</td>
        <td id="LC16013" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:EXON&quot; EXACT VAR []</td>
        <td id="LC16301" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SYNONYMOUS_CODING&quot; EXACT VAR []</td>
        <td id="LC16363" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CODON_DELETION&quot; RELATED VAR []</td>
        <td id="LC16391" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CODON_CHANGE_PLUS_CODON_INSERTION&quot; EXACT VAR []</td>
        <td id="LC16414" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CODON_CHANGE_PLUS_CODON_DELETION&quot; EXACT VAR []</td>
        <td id="LC18075" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:START_GAINED&quot; EXACT VAR []</td>
        <td id="LC18264" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:RARE_AMINO_ACID&quot; EXACT VAR []</td>
        <td id="LC18297" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:INTRAGENIC&quot; EXACT VAR []</td>
        <td id="LC18309" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:START_LOST&quot; EXACT VAR []</td>
        <td id="LC18324" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:UTR_5_DELETED&quot; EXACT VAR []</td>
        <td id="LC18345" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:UTR_3_DELETED&quot; EXACT VAR []</td>
        <td id="LC18364" class="blob-code blob-code-inner js-file-line">comment: Requested by Uma Paila (UVA) for snpEff.</td>
        <td id="LC18367" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:INTERGENIC_CONSERVED&quot; EXACT VAR []</td>
        <td id="LC18377" class="blob-code blob-code-inner js-file-line">comment: Requested by Uma Paila (UVA) for snpEff.</td>
        <td id="LC18380" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:INTRON_CONSERVED&quot; EXACT VAR []</td>
        <td id="LC18390" class="blob-code blob-code-inner js-file-line">comment: Requested by Uma Paila as this term is annotated by snpEff. This would be used for non_AUG start codon annotation.</td>
        <td id="LC18391" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:SYNONYMOUS_START&quot; EXACT VAR []</td>
        <td id="LC21435" class="blob-code blob-code-inner js-file-line">synonym: &quot;snpEff:CHROMOSOME_LARGE_DELETION&quot; EXACT VAR []</td>


Checking intron_variant, I could not see this present for snpEff in the ontology file (maybe I missed it?). 
        <td id="LC14395" class="blob-code blob-code-inner js-file-line">name: intron_variant</td>
        <td id="LC14402" class="blob-code blob-code-inner js-file-line">synonym: &quot;Jannovar:intron_variant&quot; EXACT VAR [http://doc-openbio.readthedocs.org/projects/jannovar/en/master/var_effects.html]</td>
        <td id="LC14406" class="blob-code blob-code-inner js-file-line">synonym: &quot;VAAST:intron_variant&quot; EXACT VAR []</td>
        <td id="LC14407" class="blob-code blob-code-inner js-file-line">synonym: &quot;VEP:intron_variant&quot; EXACT VAR []</td>
        <td id="LC14444" class="blob-code blob-code-inner js-file-line">is_a: SO:0001627 ! intron_variant</td>
        <td id="LC17883" class="blob-code blob-code-inner js-file-line">name: coding_transcript_intron_variant</td>
        <td id="LC17886" class="blob-code blob-code-inner js-file-line">synonym: &quot;Jannovar:coding_transcript_intron_variant&quot; EXACT VAR [http://doc-openbio.readthedocs.org/projects/jannovar/en/master/var_effects.html]</td>
        <td id="LC17887" class="blob-code blob-code-inner js-file-line">is_a: SO:0001627 ! intron_variant</td>
        <td id="LC17894" class="blob-code blob-code-inner js-file-line">name: non_coding_transcript_intron_variant</td>
        <td id="LC17897" class="blob-code blob-code-inner js-file-line">synonym: &quot;Jannovar:non_coding_transcript_intron_variant&quot; NARROW VAR [http://doc-openbio.readthedocs.org/projects/jannovar/en/master/var_effects.html]</td>
        <td id="LC17900" class="blob-code blob-code-inner js-file-line">is_a: SO:0001627 ! intron_variant</td>
        <td id="LC18375" class="blob-code blob-code-inner js-file-line">name: conserved_intron_variant</td>
        <td id="LC18379" class="blob-code blob-code-inner js-file-line">synonym: &quot;Jannovar:conserved_intron_variant&quot; EXACT VAR [http://doc-openbio.readthedocs.org/projects/jannovar/en/master/var_effects.html]</td>
        <td id="LC18382" class="blob-code blob-code-inner js-file-line">is_a: SO:0001627 ! intron_variant</td>
        <td id="LC19079" class="blob-code blob-code-inner js-file-line">name: 3_prime_UTR_intron_variant</td>
        <td id="LC19084" class="blob-code blob-code-inner js-file-line">is_a: SO:0001969 ! coding_transcript_intron_variant</td>
        <td id="LC19090" class="blob-code blob-code-inner js-file-line">name: 5_prime_UTR_intron_variant</td>
        <td id="LC19095" class="blob-code blob-code-inner js-file-line">is_a: SO:0001969 ! 
coding_transcript_intron_variant</td>

**Comment by marc-sturm** [comment]
Hi Colin,

did you also update to the corresponding SnpEff version?
I tested the so-xp_3_0_0.obo file with version 4.3i and it worked fine:
https://github.com/imgag/megSAP/blob/master/data/download_tools.sh

If that still does not help, you can simply comment out the Miso check in
check_vcf.php.
It is not really required for the pipeline :)

Best,
  Marc

**Comment by colindaven** [comment]
Thanks, tried with the current version (but slightly older snpEff hg19 db) -same error.

I commented the section out, and now have problems with mysql :)

So another couple of dependencies would be 
mysql-server php-mysql

Thanks

**Comment by marc-sturm** [comment]
Hi Colin,

Can you send me the Log files please. The steps m,vc, an should not need
mysql.

Best, Marc


Am 23.02.2017 17:01 schrieb "Colin Davenport" <notifications@github.com>:

Thanks, tried with the current version (but slightly older snpEff hg19 db)
-same error.

I commented the section out, and now have problems with mysql :)

So another couple of dependencies would be
mysql-server php-mysql

Thanks

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/imgag/megSAP/issues/5#issuecomment-282033984>, or mute
the thread

**Comment by colindaven** [comment]
Hi Marc,

this is the end of the relevant log, annotation. Mapping and SNP calling went without a hitch.

NA12878_01_log3_anno.log

`2017-02-23T16:44:35.3013        DINj    Execution time of 'annotation' pipeline: 47.1524s
2017-02-23T16:44:35.3050        DINj    END an_snpeff
2017-02-23T16:44:35.3063        DINj    Execution time of 'an_snpeff': 49.3022s
2017-02-23T16:44:35.3395        ON78    Calling external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/NGS/check_vcf.php'
2017-02-23T16:44:35.3395        ON78        version    = 0.1-58-g165f77a
2017-02-23T16:44:35.3395        ON78        parameters = -in /tmp/annotate_FOR43f.vcf -build hg19
2017-02-23T16:44:35.3395        ON78        log_id     = uqNN
2017-02-23T16:44:35.3645        uqNN    START check_vcf (version: 0.1-58-g165f77a)
2017-02-23T16:44:35.3658        uqNN    Verbose: false
2017-02-23T16:44:35.3670        uqNN    Parameter: limit = 10000
2017-02-23T16:44:35.3682        uqNN    Parameter: build = hg19
2017-02-23T16:44:35.3694        uqNN    Parameter: in    = /tmp/annotate_FOR43f.vcf
2017-02-23T16:44:36.8990        uqNN    END check_vcf
2017-02-23T16:44:36.9008        uqNN    Execution time of 'check_vcf': 1.5434s
2017-02-23T16:44:36.9122        ON78    Calling external tool '/galaxy_nfs/tools/megsap/megSAP//data/tools/ngs-bits/bin/VariantQC'
2017-02-23T16:44:36.9122        ON78        version    = 0.1-631-g9fa4741
2017-02-23T16:44:36.9122        ON78        parameters = -in /tmp/annotate_FOR43f.vcf -out Sample_NA12878_01/NA12878_01_stats_vc.qcML
2017-02-23T16:44:36.9538        ON78    Execution time of '/galaxy_nfs/tools/megsap/megSAP//data/tools/ngs-bits/bin/VariantQC': 0.0404s
2017-02-23T16:44:36.9841        ON78    Calling external tool 'php /galaxy_nfs/tools/megsap/megSAP//src/NGS/vcf2gsvar.php'
2017-02-23T16:44:36.9841        ON78        version    = 0.1-58-g165f77a
2017-02-23T16:44:36.9841        ON78        parameters = -in /tmp/annotate_FOR43f.vcf -out Sample_NA12878_01/NA12878_01.GSvar
2017-02-23T16:44:36.9841        ON78        log_id     = VKf3
2017-02-23T16:44:37.0134        VKf3    START vcf2gsvar (version: 0.1-58-g165f77a)
2017-02-23T16:44:37.0147        VKf3    Verbose: false
2017-02-23T16:44:37.0166        VKf3    Parameter: in  = /tmp/annotate_FOR43f.vcf
2017-02-23T16:44:37.0178        VKf3    Parameter: out = Sample_NA12878_01/NA12878_01.GSvar
2017-02-23T16:44:37.0424        VKf3    END vcf2gsvar
2017-02-23T16:44:37.0438        VKf3    Execution time of 'vcf2gsvar': 0.0384s
2017-02-23T16:44:37.0728        ON78    ERROR: '2017-02-23T16:44:37.0727        rcug (SYSTEM)   ERROR: SQLSTATE[42S02]: Base table or view not f
' in /galaxy_nfs/tools/megsap/megSAP/src/Common/db.php:419.
2017-02-23T16:44:37.0742        ON78    END annotate
2017-02-23T16:44:37.0754        ON78    Execution time of 'annotate': 51.1340s`

**Comment by marc-sturm** [comment]
Hi Colin,

The pipeline is basically through at that point.
The _var_annotated.vcf.gz file and the GSvar file (an Excel-compatible
variant list) should be created and ready to use.

I found the bug and will fix it on monday. Today I'm not at work.
VariantAnnotateNGSD is executed without checking if the NGSD is available.
For now, you can comment out the line containing "VariantAnnotateNGSD" in
annotate.php.

Best,
  Marc

**Comment by colindaven** [comment]
Hi Marc,

thanks for this and all the support. I have very nice results for the sample file now, and think this looks very useful for some of my own data. 

I'll look forwards to updating again in the future to get some of these bugfixes in.

thanks,
Colin

**Comment by imgag** [comment]
Hi Colin,

thanks for your feedback.

Don't hesitate to contect me with any bug reports or comments.

Best,
  Marc
