### ISSUE TITLE
cfDNA: Allow monitoring of tumor progression

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#53]
megSAP:
  - nur ein Prozessierungssystem anlegen, nicht eins pro Patient (Typ "cfDNA (patient-specific)")

  - Es wird nur Mapping und VariantenCalling gemacht (bis GSvar)

  - VariantCalling auf den gesamten Daten oder wenn vorhanden über Zielregion (ID SNPs) zusammen mit patientenspezifischen SNPs unter [data_folder]\enrichment\patient-specific\\[system_name]\\[tumor_ps].bed 

GSvar (Personalisiertes Design):

  - Tumor öffnen > Button in Toolbar von Variantenliste  > "design personalized cfDNA panel"

  - Filtert Tumorvarianten (Filterspalte leer, nicht als Artefakt geflaggt in report config, driver immer, über Chromosome verteilt, varianten +-10 Basen nur ein Mal zählen), Rankt nach Tumur AF, Wählt top x > Variaten aus
  
  - Fragt user nach Prozessierungssystem (cfDNA) und schreibt VCF/BED-File nach [data_folder]\enrichment\patient-specific\\[system_name]\\[tumor_ps].bed

GSvar (Verlaufskontrolle):

  - Tumor öffnen > Button in Toolbar von Variantenliste > "course of the disease (personalized cfDNA)" > neues Widget anzeigen.

  - Das Widget stellt die AF der Variaten dar für Tumor, cf1, cf2, ... (tabelle + graphik)

     - als Zeitpunkt nehmen wir "sample - received" aus der NGSD

     - es werden alle cfDNA-Proben des selben "sample" oder von samples die als "same_sample" geflaggt sind angezeigt.

  - Aus dem Widget kann man einen Report mit Tabelle und Plots erzeugen.

**Comment by marc-sturm** [comment]
**Email from Jakob:**

Pipeline analyze_cfdna.php
•	führt Alignment und Variant Calling durch
•	prüft Zugehörigkeit zum Tumor (Tumor-ID wird über sample relations gesucht)
•	kann für alle Proben mit Processing System vom Typ "cfDNA (patient-specific)" genutzt werden
•	benötigt ein Patient BED-File übergeben oder am Standardort data/enrichment/patient-specific/<system name short>/<tumor id>.bed
•	neue Proben werden mit dieser Pipeline über die Queue gerechnet
•	Test der Pipeline in test/data_cfdna (Makefile)


Variant Caller Wrapper vc_cfdna.php
•	ruft cfdna_caller auf
•	Error Modell kann gespeichert werden pro Processing System: data/dbs/cfdna_caller/<system name short>.txt , ist für IDT_xGenPrism abgelegt
•	installiert unter: /mnt/share/opt/cfdna_variant_caller/cfdna_caller.sh 
•	Repository (noch privat für IMGAG): https://github.com/imgag/cfdna_variant_caller 

TODOs
•	nochmals gründlich testen und dann merge möglich
•	barcode_correction.py kompatibel mit Python3 machen
•	cfdna_variant_caller: Indel Detektion oder Ausgabe muss kontrolliert werden

**Comment by marc-sturm** [comment]
Also have a look at the issues:
https://github.com/imgag/cfdna_variant_caller/issues

**Comment by leonschuetz** [comment]
Additional tasks:
 - add Genes/ VEP annotation to disease course widget
- add p-value, alt count and depth as tool tip to disease course widget
- add number of selected variants to design widget
- make tumor relation mandatory for cfDNA processed sample import
- add visualisation to disease course widget
- check bedfile (same pos of start/end)

**Comment by leonschuetz** [comment]
tasks resolved in commit 888f420b8d7e00b4ead42146c98d2b3ee2ccf41a :
 - add Genes/ VEP annotation to disease course widget
 - add p-value, alt count and depth as tool tip to disease course widget
 - add number of selected variants to design widget
 - make tumor relation mandatory for cfDNA processed sample import
 - check bedfile (same pos of start/end)

still open tasks:
 - add visualisation to disease course widget

new additional tasks:
 - IGV support for cfDNA widget
 - export for cfDNA widget
 - allow to load/edit panel designs
 - allow select all for SNPs/hotspot regions
 - ( come up with a solution to display genes/hotspot regions)
 -  apply filters from MainWindow
 -  ( folder for IDT BED files)

**Comment by leonschuetz** [comment]
additional tasks: 
- IGV support for DesignPanel
- apply MainWindow filters and load previously selected variants (missing variants are appended to the var list with a notice)
- add gene name to design panel

**Comment by leonschuetz** [comment]
- fix VCF
- add/check monitoring SNPs (IDT SNPs)
- Batchimport cfDNA panels + sample relations
- annotation of normal AF/Counts
- reannotation of cfDNA samples
- remove regions which were removed by IDT

**Comment by leonschuetz** [comment]
Todo summary

- [ ] add visualisation to disease course widget
- [ ] allow to load/edit panel designs
- [ ] allow select all for SNPs/hotspot regions
- [ ] ( come up with a solution to display genes/hotspot regions)
- [ ] apply filters from MainWindow
- [ ] ( folder for IDT BED files)
- [ ] IGV support for DesignPanel
- [ ] apply MainWindow filters and load previously selected variants (missing variants are appended to the var list with a notice)
- [ ] add gene name to design panel
- [ ] fix VCF
- [ ] add/check monitoring SNPs (IDT SNPs)
- [ ] Batchimport cfDNA panels
- [ ] Batchimport cfDNA sample relations
- [ ] annotation of normal AF/Counts
- [ ] reannotation of cfDNA samples
- [ ] remove regions which were removed by IDT

**Comment by leonschuetz** [comment]
- [ ] add GSvar functionality to (re-)start cfDNA samples

**Comment by leonschuetz** [comment]
- [ ] adapt map.qcML and NGSD to cfDNA (new ngs-bits tool?)
      add the following parameter:
      - Similarity zu NGSD Referenzprobe (KSAP, falls verfügbar, inkl. ID Referenzprobe)
      - Durchschnittl. Tiefe undedupliziert
      - Durchschnittl. Tiefe dedupliziert (= Fragmente cfDNA, ggf. bereits in map.qcML)
      - Eingesetzte DNA-Menge in ng
      - Histogramm der Duplikate mit count Reads (hier hat Fran bereits irgendwo in den Unterordnern die Daten)
      - Verteilung der Fragementlängen / Insert sizes als line plot (schon im map.qcML, kann hier die erwartete cfDNA Länge von ca. 166 bp mittels Linie markiert werden?)
      - Depth of coverage plot dedupliziert (schon in map.qcML, hört jedoch viel zu früh bei 3000x auf)
      - Coverage zu bestimmten Tiefen (schon in map.qcML, hört jedoch viel zu früh bei 500x auf)
      - Zahl der verwendeten Barcodes (?)
      - Weitere?

**Comment by leonschuetz** [comment]
Additional task from the meeting (16.11.21):

- [ ]  implement QC parameter (cov mon/ID, error rates, tumor similarity, cfDNA similarity...) as presented
- [ ] threshold for samples (monitoring): avg: >1000x, single variants: >250x
- [ ] check on-target computation

**Comment by leonschuetz** [comment]
GSvar-Panel Design: 
- [ ] Use pre-selection from sample folder
- [ ] Allow adding of not-called Variants
