### ISSUE TITLE
Installation issue with download_tools_rna.sh

### ISSUE THREAD

**Issue by mschindl** [imgag/megSAP#72]
Subred, Skewer and Salmon will not be installed properly, it's missing in ./tools
Tools installed in "tools/igv-reports-0.9.1/", because of last "cd" in line24 "cd igv-reports-0.9.1"

![image](https://user-images.githubusercontent.com/26382876/99067357-de596280-25aa-11eb-8a30-b5131051aaba.png)

**Comment by marc-sturm** [comment]
Hi Marc,

does this problem pothis the current master?

Best,
  Marc

**Comment by mschindl** [comment]
It seems to be fixed with "build && cd .."
