### ISSUE TITLE
Add support for SVs to trio/multi pipelines.

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#74]
Implementation unclear:
- Use multi-sample calling for SVs or combine SV calls from several samples?
- BEDPE with several samples possible?

**Comment by leonschuetz** [comment]
Implemented SV multisample/trio calling in a6e1a498c8db48b05e588bb57c09c676bc93b65f

**Comment by leonschuetz** [comment]
added trio/multisample SV support in ngs-bits [01ea3dd](https://github.com/imgag/ngs-bits/commit/01ea3dd755f891e7d51f4a68126eaad13b9a0276)
