### ISSUE TITLE
use ReViewer to visualize repeat expansions

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#84]
call ReViewer for each repeat and store the SVGs in the sub-folder "repeat_expansions" of the sample filter.

Add context menu entry in GSvar to show the SVG for a repeat.

ReViewer:
https://emea.illumina.com/science/genomics-research/reviewer-visualizing-alignments-short-reads-long-repeat.html

**Comment by leonschuetz** [comment]
integrated in megSAP in 86e4269e9d45212042d51c649d8f9c9120e45572

GSvar support integrated in ngs-bits commit [208c5d1](https://github.com/imgag/ngs-bits/commit/208c5d1c957fec6d46c2f460b4dd51713d07b441)
