### ISSUE TITLE
use local BAM for variant calling

### ISSUE THREAD

**Issue by marc-sturm** [imgag/megSAP#88]
Use a local copy of the BAM file for variant calling:
- provide tmp BAM file path to mapping.php and re-use that BAM for variant calling (the BAM is still copied to the output folder)
- if no mapping was performed and the analysis is not "annotation_only", copy the BAM file from the analysis folder to the local tmp

**Comment by leonschuetz** [comment]
Implemented in commit b3a96396b46318129f44a847b2f7028f02c6e3ec
