### ISSUE TITLE
Unbundle Data ?

### ISSUE THREAD

**Issue by apeltzer** [imgag/megSAP#9]
Hi !

we're planning to use the pipeline for several projects but would like to modularize things here. Especially get rid of the necessity to have the DB data inside a container image. Is it possible to externalize this somehow and maybe set this as a path where all the database content is stored instead? This would greatly improve handling of the containers - and we could still have updated databases whenever this is required due to changes there, too. 

In the other way every container has ~32GB of data, which is a bit too much for handling things properly.

**Comment by imgag** [comment]
That is possible by moving the 'data' folder out of the container and bind the external path to the 'data' folder when executing the container.
