### ISSUE TITLE
[How to] convert vcf to annotated GSvar

### ISSUE THREAD

**Issue by damianosmel** [imgag/megSAP#93]
Dear GSvar team,

by my last issue, I got the installation of the megSAP on a ubuntu docker to finish without errors. 

My main goal to use megSAP is to annotate an input vcf file using vep and then convert it to GSvar.
My collaborators from the MHH, told me about [an_vep.php](https://github.com/imgag/megSAP/blob/master/src/NGS/an_vep.php) and [annotate.php](https://github.com/imgag/megSAP/blob/master/src/Pipelines/annotate.php).
However, after the successful installation I have get the following error output by running:

`php an_vep.php -in /home/example_vcfs/diaph1.vcf -out /home/example_vcfs/diaph1_annot.vcf >& an_vep.txt`
Please see the output at: [an_vep.txt](https://github.com/imgag/megSAP/files/6663318/an_vep.txt)

Then, I have seen the data_setup in an_vep.php so I thought to run it myself.
I did that by:
`php data_setup.php -build GRCh37 >& data_setup.txt`
Please see the output at: [data_setup.txt](https://github.com/imgag/megSAP/files/6663321/data_setup.txt)

As you see this is not also successful as it **assumes** as local_data folder the /tmp which is not mounted space of the container that megSAP is installed in.

I have just tried also with the annotate.php, by running:
`php annotate.php -out_name diaph1 -out_folder /megSAP/example_runs >& /megSAP/annotate.txt`
Please see the output at: [annotate.txt](https://github.com/imgag/megSAP/files/6663427/annotate.txt)

My current questions are:
1) which tools and in what sequence I should run them to get from a vcf file to GSvar that contains the vep annotation of the vcf?
2) please can you give the example run arguments for this sequence of tools

Thank you in advance for your help :)

Best,
Damianos

**Comment by marc-sturm** [comment]
Hi Damianos,

starting from VCF can be done, but I would suggest you start from variant calling.
The annotation step assumes that the VCF is normalized in a certain way, which it is probably not in your case.

The local data folder of megSAP can be definined in the settings.ini file.
A template for the settings.ini can be found here:
https://github.com/imgag/megSAP/blob/master/settings.ini.default
Then the data_setup.php should run through.

After that the an_vep and vcf2gsvar can be executed.

Best,
  Marc

**Comment by damianosmel** [comment]
Hi Marc,

I could run the an_vep with errors only on the splicing algorithms.
Then I have reinstalled tensorflow 2.2 on the python splicing environment (first made by download_tools.sh)
Still the splicing did not work: [an_vep_tensorflow.log](https://github.com/imgag/megSAP/files/6669821/an_vep_tensorflow.log)

Then I have selected to run without the splicing predictions and the gsvar is created.

However, my main concern is on the vcf2gsvar.php as it does run through,
command:
`php src/NGS/vcf2gsvar.php -in example_runs/diaph1_annot.vcf -out example_runs/diaph1_annot.GSvar --debug >& vcf2gsvar.log`
log: 
[vcf2gsvar.log](https://github.com/imgag/megSAP/files/6669823/vcf2gsvar.log)

In your reply, you mention about normalization of the VCF; this may relates to the vcf2gsvar error?

Our plan is:
use our tool to classify variants for genetic hearing loss.
a) This tool can be run through command line having as input a folder containing files, each being a WES of patient formatted in GSvar.
b) The tool can be also run through web. There the use gives as input a **single** variant, formatted as its chrom, start, stop, ref, alt. Then in the backend the tool is run through to get the classification.

For the a) the colleagues from human genetics department of MHH they have already used your team's megSAP to map,annotate and format in gsvar input WES data. Then I have developed the tool with GSvar as input.

Thus for the b), I need to run megSAP internally and get the GSvar file for the single variant of the user. Then I can run the classification tool.

Based on this scheme may you please suggest how I can solve the running error of the vcf2gsvar?

Thank you,
Damianos

**Comment by marc-sturm** [comment]
Hi Damianos,

the first error is a mmSplice error. I cannot really help there.
Maybe this thread helps you:
https://stackoverflow.com/questions/1210664/no-module-named-sqlite3

The second error looks like your input VCF is corrupt or already in GSvar format, probably the second.
You have to provide valid VCF as input.
You can check the VCF e.g. with VcfCheck of ngs-bits.

Best,
  Marc

**Comment by damianosmel** [comment]
Dear Mark,

when I am running the `an_vep.php` disabling the splicing option, I still get the MMSplice and SpliceAI predictions. So I discontinue to re-install the splicing tools.

About the vcf file, if I input a valid formatted VCF file the `vcf2gsvar.php` works without errors.

Thank you very much for your help,
Damianos
