### ISSUE TITLE
Question: VCF specifications for correct run of an_vep.php

### ISSUE THREAD

**Issue by damianosmel** [imgag/megSAP#98]
Dear megSAP developers team,

I have integrated megSAP in our bioinformatics application through docker.
I use megSAP to convert a vcf file to GSvar and then use our tool code.

For this first step conversion vcf -> annotated.vcf -> annotated.GSvar
I use the an_vep.php and vcf2gsvar.php scripts as follows:
1. `>php an_vep.php -in /megSAP/example_runs/example_var.vcf -out /megSAP/example_runs/example_var.vcf -no_splice >& /megSAP/an_vep_example_var.log
`
2. `>php /megSAP/src/NGS/vcf2gsvar.php -in /megSAP/example_var_annot.vcf -out /megSAP/example_var_annot.GSvar >& /megSAP/vcf2gsvar_example_var.log`

For the second command I know that I need a VCF file that contains genotype information (GT), otherwise vcf2gsvar will complain and produce an **empty** GSvar output file.

I was experimenting with some more VCF inputs and I have found that for some the 1) step can also complain and no produce an annotated vcf file at all.
I attach this vcf file and the logs running 1) and 2) on it.
I also attach two vcfs (their general format) that works for both steps without errors.

My question is: what are the vcf input specifications for the two steps to run without errors?
Then I can write up an informative message for the user of this tool
(Up to now, I ask the user for a VCF of 4.1+ format with GT information per sample)

Thank you very much,
Damianos
[not_working_vcf.txt](https://github.com/imgag/megSAP/files/7259624/not_working_vcf.txt)
[no_working_vcf_annot.log](https://github.com/imgag/megSAP/files/7259625/no_working_vcf_annot.log)
[no_working_vcf_gsvar.log](https://github.com/imgag/megSAP/files/7259626/no_working_vcf_gsvar.log)
[working1_vcf.txt](https://github.com/imgag/megSAP/files/7259631/working1_vcf.txt)
[working2_vcf.txt](https://github.com/imgag/megSAP/files/7259633/working2_vcf.txt)

**Comment by marc-sturm** [comment]
Hi Damianos,

there was a bug in VcfAnnotateFromVcf that caused the error message to be not printed.
I fixed that bug: https://github.com/imgag/ngs-bits/commit/3336ff0a9772f72d013031176cba10ca62fcfa88
If you use the master of ngs-bits you should see the error message now.

The problem is that the file is already annotated.
Here my test output:
![grafik](https://user-images.githubusercontent.com/5638144/135475042-8746b541-0895-4139-8873-d39f8cb1b507.png)

Best,
  Marc

**Comment by damianosmel** [comment]
I understand Marc, thank you very much!
